'use server';

/**
 * @fileOverview Generates a detailed feedback report for a given text and its corrected version.
 *
 * - generateFeedbackReport - A function that generates the feedback report.
 * - GenerateFeedbackReportInput - The input type for the generateFeedbackReport function.
 * - GenerateFeedbackReportOutput - The return type for the generateFeedbackReport function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateFeedbackReportInputSchema = z.object({
  originalText: z.string().describe('The original text submitted by the user.'),
  correctedText: z.string().describe('The corrected text generated by the AI.'),
});
export type GenerateFeedbackReportInput = z.infer<typeof GenerateFeedbackReportInputSchema>;

const GenerateFeedbackReportOutputSchema = z.object({
  report: z.string().describe('A detailed feedback report highlighting error percentage, areas for improvement, and specific suggestions.'),
});
export type GenerateFeedbackReportOutput = z.infer<typeof GenerateFeedbackReportOutputSchema>;

export async function generateFeedbackReport(input: GenerateFeedbackReportInput): Promise<GenerateFeedbackReportOutput> {
  return generateFeedbackReportFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateFeedbackReportPrompt',
  input: {schema: GenerateFeedbackReportInputSchema},
  output: {schema: GenerateFeedbackReportOutputSchema},
  prompt: `You are an AI writing assistant that generates feedback reports for users to improve their writing skills.

You will receive the original text and the corrected text. Analyze the differences between the two texts to identify areas where the user can improve.

Provide a comprehensive report that includes:
- The percentage of errors detected in the original text.
- Specific examples of errors in grammar, spelling, and punctuation.
- Suggestions for improving in these areas, tailored to the identified errors.

Original Text: {{{originalText}}}
Corrected Text: {{{correctedText}}}

Generate Feedback Report: `,
});

const generateFeedbackReportFlow = ai.defineFlow(
  {
    name: 'generateFeedbackReportFlow',
    inputSchema: GenerateFeedbackReportInputSchema,
    outputSchema: GenerateFeedbackReportOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
